"""add cascade deletes

Revision ID: 838074132a62
Revises: 5e6cea237e62
Create Date: 2026-05-08 21:01:31.854620

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '838074132a62'
down_revision: Union[str, Sequence[str], None] = '5e6cea237e62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chunks_document_id_fkey'), 'chunks', type_='foreignkey')
    op.create_foreign_key(None, 'chunks', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('documents_user_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('embeddings_chunk_id_fkey'), 'embeddings', type_='foreignkey')
    op.create_foreign_key(None, 'embeddings', 'chunks', ['chunk_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'embeddings', type_='foreignkey')
    op.create_foreign_key(op.f('embeddings_chunk_id_fkey'), 'embeddings', 'chunks', ['chunk_id'], ['id'])
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_user_id_fkey'), 'documents', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.create_foreign_key(op.f('chunks_document_id_fkey'), 'chunks', 'documents', ['document_id'], ['id'])
    # ### end Alembic commands ###
